apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    route:
      receiver: 'slack-alert'
    receivers:
      - name: 'slack-alert'
        slack_configs:
          - channel: "#alerts"
            send_resolved: true
            text: "{{ .CommonAnnotations.summary }}"
