apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eks-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: eks-metrics
  endpoints:
    - port: http
      interval: 30s
